site_name: Software Engineering Leaders

nav:
  - Home: index.md
  - Course Description: course-description.md
  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept Enumeration: learning-graph/concept-list.md
    - Graph Quality Analysis: learning-graph/quality-metrics.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Taxonomy Distribution Report: learning-graph/taxonomy-distribution.md
  - MicroSims:
    - Graph Viewer: sims/graph-viewer/index.md
